DFRobotMaqueenPlus.I2CInit()
DFRobotMaqueenPlus.mototRun(Motors.ALL, Dir.CW, 60)
basic.pause(700)
DFRobotMaqueenPlus.mototStop(Motors.ALL)
basic.pause(500)
DFRobotMaqueenPlus.mototRun(Motors.M1, Dir.CW, 50)
basic.pause(700)
DFRobotMaqueenPlus.mototStop(Motors.ALL)
basic.pause(500)
DFRobotMaqueenPlus.mototRun(Motors.M2, Dir.CW, 50)
basic.pause(700)
DFRobotMaqueenPlus.mototStop(Motors.ALL)
basic.pause(500)
DFRobotMaqueenPlus.mototRun(Motors.M2, Dir.CW, 50)
basic.pause(700)
DFRobotMaqueenPlus.mototStop(Motors.ALL)
basic.pause(500)
DFRobotMaqueenPlus.mototRun(Motors.M1, Dir.CW, 50)
basic.pause(700)
DFRobotMaqueenPlus.mototStop(Motors.ALL)
basic.pause(500)
DFRobotMaqueenPlus.mototRun(Motors.ALL, Dir.CCW, 50)
basic.pause(800)
DFRobotMaqueenPlus.mototStop(Motors.ALL)
basic.pause(500)
DFRobotMaqueenPlus.mototRun(Motors.M1, Dir.CW, 50)
basic.pause(700)
