for (let index = 0; index < 2; index++) {
    DFRobotMaqueenPlus.I2CInit()
    DFRobotMaqueenPlus.mototRun(Motors.ALL, Dir.CW, 60)
    basic.pause(200)
    DFRobotMaqueenPlus.mototStop(Motors.ALL)
    basic.pause(500)
    DFRobotMaqueenPlus.mototRun(Motors.M1, Dir.CW, 82)
    basic.pause(200)
    DFRobotMaqueenPlus.mototStop(Motors.M1)
    basic.pause(500)
    DFRobotMaqueenPlus.mototRun(Motors.M2, Dir.CW, 82)
    basic.pause(200)
    DFRobotMaqueenPlus.mototStop(Motors.M2)
    basic.pause(500)
    DFRobotMaqueenPlus.mototRun(Motors.M1, Dir.CW, 82)
    basic.pause(200)
    DFRobotMaqueenPlus.mototStop(Motors.M1)
    basic.pause(500)
    DFRobotMaqueenPlus.mototRun(Motors.M2, Dir.CW, 82)
    basic.pause(200)
    DFRobotMaqueenPlus.mototStop(Motors.M2)
    basic.pause(500)
    DFRobotMaqueenPlus.mototRun(Motors.M1, Dir.CW, 82)
    basic.pause(200)
    DFRobotMaqueenPlus.mototStop(Motors.M1)
    basic.pause(500)
    DFRobotMaqueenPlus.mototRun(Motors.M2, Dir.CW, 82)
    basic.pause(200)
    DFRobotMaqueenPlus.mototStop(Motors.M2)
    basic.pause(500)
    DFRobotMaqueenPlus.mototRun(Motors.ALL, Dir.CCW, 72)
    basic.pause(200)
    DFRobotMaqueenPlus.mototStop(Motors.ALL)
    basic.pause(200)
    DFRobotMaqueenPlus.mototRun(Motors.M1, Dir.CW, 72)
    basic.pause(200)
    DFRobotMaqueenPlus.mototStop(Motors.ALL)
}
basic.forever(function () {
	
})
basic.forever(function () {
    basic.pause(500)
    DFRobotMaqueenPlus.setRGBLight(RGBLight.RGBA, Color.RED)
    basic.pause(100)
    DFRobotMaqueenPlus.setRGBLight(RGBLight.RGBA, Color.GREEN)
    basic.pause(100)
    DFRobotMaqueenPlus.setRGBLight(RGBLight.RGBA, Color.BLUE)
    basic.pause(100)
    DFRobotMaqueenPlus.setRGBLight(RGBLight.RGBA, Color.YELLOW)
    basic.pause(100)
    DFRobotMaqueenPlus.setRGBLight(RGBLight.RGBA, Color.RED)
    basic.pause(100)
    DFRobotMaqueenPlus.setRGBLight(RGBLight.RGBA, Color.GREEN)
    basic.pause(100)
    DFRobotMaqueenPlus.setRGBLight(RGBLight.RGBA, Color.BLUE)
    basic.pause(100)
    DFRobotMaqueenPlus.setRGBLight(RGBLight.RGBA, Color.YELLOW)
    basic.pause(100)
    DFRobotMaqueenPlus.setRGBLight(RGBLight.RGBA, Color.PINK)
    basic.pause(100)
    DFRobotMaqueenPlus.setRGBLight(RGBLight.RGBA, Color.CYAN)
    basic.pause(100)
    DFRobotMaqueenPlus.setRGBLight(RGBLight.RGBA, Color.WHITH)
    DFRobotMaqueenPlus.setRGBLight(RGBLight.RGBA, Color.OFF)
})
